"""location module

Revision ID: 492d48dd33f6
Revises: bbbff13324e2
Create Date: 2026-09-06 14:18:46.308640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '492d48dd33f6'
down_revision: Union[str, Sequence[str], None] = 'bbbff13324e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('street')
    op.add_column('regions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('regions', 'cteated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('cteated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('regions', 'created_at')
    op.create_table('street',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ward_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('street_ward_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('street_pkey'))
    )
    op.drop_table('streets')
    # ### end Alembic commands ###
