"""media model

Revision ID: bb5153b9bc4f
Revises: 
Create Date: 2026-09-11 13:41:21.162449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5153b9bc4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('new_filename', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('customers', 'profile_picture',
               new_column_name='profile_picture_legacy')
    op.add_column('customers', sa.Column('profile_picture', sa.Integer(), nullable=True))
    op.execute(sa.text("""
        INSERT INTO media (path, uploaded_by)
        SELECT profile_picture_legacy, id
        FROM customers
        WHERE profile_picture_legacy IS NOT NULL
          AND btrim(profile_picture_legacy) <> ''
    """))
    op.execute(sa.text("""
        UPDATE customers AS c
        SET profile_picture = m.id
        FROM media AS m
        WHERE m.uploaded_by = c.id
          AND m.path = c.profile_picture_legacy
    """))
    op.drop_column('customers', 'profile_picture_legacy')
    op.create_foreign_key(None, 'customers', 'media', ['profile_picture'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.add_column('customers', sa.Column('profile_picture_legacy', sa.VARCHAR(), nullable=True))
    op.execute(sa.text("""
        UPDATE customers AS c
        SET profile_picture_legacy = m.path
        FROM media AS m
        WHERE m.id = c.profile_picture
    """))
    op.drop_column('customers', 'profile_picture')
    op.alter_column('customers', 'profile_picture_legacy',
               new_column_name='profile_picture')
    op.drop_table('media')
    # ### end Alembic commands ###
