"""location module

Revision ID: bf57d1f2e29a
Revises: 492d48dd33f6
Create Date: 2026-09-06 14:43:30.537477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf57d1f2e29a'
down_revision: Union[str, Sequence[str], None] = '492d48dd33f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wards', sa.Column('district_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('wards_disrtrict_id_fkey'), 'wards', type_='foreignkey')
    op.create_foreign_key(None, 'wards', 'districts', ['district_id'], ['id'])
    op.drop_column('wards', 'disrtrict_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wards', sa.Column('disrtrict_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wards', type_='foreignkey')
    op.create_foreign_key(op.f('wards_disrtrict_id_fkey'), 'wards', 'districts', ['disrtrict_id'], ['id'])
    op.drop_column('wards', 'district_id')
    # ### end Alembic commands ###
